export const data = [
  {
    id: 1,
    chemical_name: "Ammonium Persulfate",
    vendor: "LG Chem",
    density: 3525.92,
    viscosity: "60.63l",
    packaging: "Bag",
    pack_size: 100.0,
    unit: "kg",
    quantity: 6495.18,
  },
  {
    id: 2,
    chemical_name: "Caustic Potash",
    vendor: "Formosa",
    density: 3172.15,
    viscosity: "48.22",
    packaging: "Bag",
    pack_size: 100.0,
    unit: "kg",
    quantity: 8751.9,
  },
  {
    id: 3,
    chemical_name: "Mono Ammonium Phosphate",
    vendor: "Sinopec",
    density: 1597.65,
    viscosity: "76.51",
    packaging: "Bag",
    pack_size: 105.0,
    unit: "kg",
    quantity: 8183.73,
  },
  {
    id: 4,
    chemical_name: "n-Pentane",
    vendor: "Sinopec",
    density: 4535.26,
    viscosity: "60.76",
    packaging: "N/A",
    pack_size: "N/A",
    unit: "t",
    quantity: 6272.34,
  },
  {
    id: 5,
    chemical_name: "Ammonium Persulfate",
    vendor: "LG Chem",
    density: 3525.92,
    viscosity: "60.63l",
    packaging: "Bag",
    pack_size: 100.0,
    unit: "kg",
    quantity: 6495.18,
  },
  {
    id: 6,
    chemical_name: "Caustic Potash",
    vendor: "Formosa",
    density: 3172.15,
    viscosity: "48.22",
    packaging: "Bag",
    pack_size: 100.0,
    unit: "kg",
    quantity: 8751.9,
  },
  {
    id: 7,
    chemical_name: "Mono Ammonium Phosphate",
    vendor: "Sinopec",
    density: 1597.65,
    viscosity: "76.51",
    packaging: "Bag",
    pack_size: 105.0,
    unit: "kg",
    quantity: 8183.73,
  },
  {
    id: 8,
    chemical_name: "n-Pentane",
    vendor: "Sinopec",
    density: 4535.26,
    viscosity: "60.76",
    packaging: "N/A",
    pack_size: "N/A",
    unit: "t",
    quantity: 6272.34,
  },
];
